#!/bin/sh
set -e

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║       pdf-dispatch-tester                ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── Detect Docker host IP ─────────────────────────────────────────────────────
# Python is guaranteed available in this image.
# Reads /proc/net/route directly — no external tools needed.
DOCKER_HOST_IP=$(python3 - << 'PY'
import socket, struct
with open('/proc/net/route') as f:
    for line in f.readlines()[1:]:
        fields = line.strip().split()
        if fields[1] == '00000000':
            gw = struct.unpack('<L', bytes.fromhex(fields[2]))[0]
            print(socket.inet_ntoa(struct.pack('>L', gw)))
            break
PY
)

echo "Docker host IP (NAS gateway): ${DOCKER_HOST_IP}"

RESOLVED_SERVER="${TESTER_SERVER:-http://${DOCKER_HOST_IP}:5881}"
RESOLVED_WEBHOOK_HOST="${WEBHOOK_HOST:-${DOCKER_HOST_IP}}"
WEBHOOK_PORT="${WEBHOOK_PORT:-5882}"

# ── Generate config.yaml ──────────────────────────────────────────────────────
CONFIG=/app/config.yaml
echo "Generating config.yaml..."

cat > "$CONFIG" << YAML
# Auto-generated by entrypoint.sh — do not edit manually.

server:    "${RESOLVED_SERVER}"
api_key:   "${TESTER_API_KEY:-pdf-dispatch-test-key}"
data_path: "${TESTER_DATA:-/data}"

webhook_host: "${RESOLVED_WEBHOOK_HOST}"
webhook_port: ${WEBHOOK_PORT}

smtp:
  host:     "${SMTP_HOST:-}"
  port:     ${SMTP_PORT:-587}
  user:     "${SMTP_USER:-}"
  password: "${SMTP_PASSWORD:-}"

imap:
  host:     "${IMAP_HOST:-}"
  port:     ${IMAP_PORT:-993}
  user:     "${IMAP_USER:-}"
  password: "${IMAP_PASSWORD:-}"
  folder:   "${IMAP_FOLDER:-INBOX}"
YAML

echo "  server:       ${RESOLVED_SERVER}"
echo "  api_key:      ${TESTER_API_KEY:-pdf-dispatch-test-key}"
echo "  data_path:    ${TESTER_DATA:-/data}"
echo "  webhook_host: ${RESOLVED_WEBHOOK_HOST}"
echo "  webhook_port: ${WEBHOOK_PORT}"
echo ""

# ── Install dependencies ──────────────────────────────────────────────────────
echo "Installing Python dependencies..."
pip install -r requirements.txt -q
echo ""

# ── Wait for pdf-dispatch ─────────────────────────────────────────────────────
echo "Waiting for pdf-dispatch at ${RESOLVED_SERVER}..."
MAX=30
i=0
until wget -qO- "${RESOLVED_SERVER}/healthz" > /dev/null 2>&1; do
    i=$((i + 1))
    if [ $i -ge $MAX ]; then
        echo ""
        echo "ERROR: pdf-dispatch not reachable after ${MAX}s"
        echo "  URL:     ${RESOLVED_SERVER}"
        echo "  Gateway: ${DOCKER_HOST_IP}"
        exit 1
    fi
    printf "."
    sleep 1
done
echo " OK"
echo ""

# ── Run pytest ────────────────────────────────────────────────────────────────
ARGS="${PYTEST_ARGS:--v --tb=short}"
echo "Running: pytest ${ARGS}"
echo ""

exec python -m pytest $ARGS
