#!/bin/sh
set -e

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║       pdf-dispatch-tester                ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── Generate config.yaml ──────────────────────────────────────────────────────
CONFIG=/app/config.yaml
echo "Generating config.yaml..."

cat > "$CONFIG" << YAML
# Auto-generated by entrypoint.sh — do not edit manually.

server:    "${TESTER_SERVER:-http://pdf-dispatch-test:5000}"
api_key:   "${TESTER_API_KEY:-pdf-dispatch-test-key}"
data_path: "${TESTER_DATA:-/data}"

webhook_host: "${WEBHOOK_HOST:-pdf-dispatch-tester}"
webhook_port: ${WEBHOOK_PORT:-5882}

smtp:
  host:     "${SMTP_HOST:-}"
  port:     ${SMTP_PORT:-587}
  user:     "${SMTP_USER:-}"
  password: "${SMTP_PASSWORD:-}"

imap:
  host:     "${IMAP_HOST:-}"
  port:     ${IMAP_PORT:-993}
  user:     "${IMAP_USER:-}"
  password: "${IMAP_PASSWORD:-}"
  folder:   "${IMAP_FOLDER:-INBOX}"
YAML

echo "  server:       ${TESTER_SERVER:-http://pdf-dispatch-test:5000}"
echo "  api_key:      ${TESTER_API_KEY:-pdf-dispatch-test-key}"
echo "  data_path:    ${TESTER_DATA:-/data}"
echo "  webhook_host: ${WEBHOOK_HOST:-pdf-dispatch-tester}"
echo "  webhook_port: ${WEBHOOK_PORT:-5882}"
echo ""

# ── Install dependencies ──────────────────────────────────────────────────────
echo "Installing Python dependencies..."
pip install -r requirements.txt -q
echo ""

# ── Wait for pdf-dispatch ─────────────────────────────────────────────────────
SERVER="${TESTER_SERVER:-http://pdf-dispatch-test:5000}"
echo "Waiting for pdf-dispatch at ${SERVER}..."
MAX=30
i=0
until wget -qO- "${SERVER}/healthz" > /dev/null 2>&1; do
    i=$((i + 1))
    if [ $i -ge $MAX ]; then
        echo ""
        echo "ERROR: pdf-dispatch not reachable after ${MAX}s — ${SERVER}"
        exit 1
    fi
    printf "."
    sleep 1
done
echo " OK"
echo ""

# ── Run pytest ────────────────────────────────────────────────────────────────
ARGS="${PYTEST_ARGS:--v --tb=short}"
echo "Running: pytest ${ARGS}"
echo ""

exec python -m pytest $ARGS
