#!/bin/sh
# entrypoint.sh — tester container startup
# Generates config.yaml from environment variables, then runs pytest.

set -e

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║       pdf-dispatch-tester                ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── Generate config.yaml from environment variables ───────────────────────────
CONFIG=/app/config.yaml

echo "Generating config.yaml from environment variables..."

cat > "$CONFIG" << YAML
# Auto-generated by entrypoint.sh — do not edit manually
# Edit environment variables in the Portainer stack instead.

server:   "${TESTER_SERVER:-http://pdf-dispatch-test:5000}"
api_key:  "${TESTER_API_KEY:-pdf-dispatch-test-key}"
data_path: "${TESTER_DATA:-/data}"

smtp:
  host:     "${SMTP_HOST:-}"
  port:     ${SMTP_PORT:-587}
  user:     "${SMTP_USER:-}"
  password: "${SMTP_PASSWORD:-}"

imap:
  host:     "${IMAP_HOST:-}"
  port:     ${IMAP_PORT:-993}
  user:     "${IMAP_USER:-}"
  password: "${IMAP_PASSWORD:-}"
  folder:   "${IMAP_FOLDER:-INBOX}"
YAML

echo "  server:    ${TESTER_SERVER:-http://pdf-dispatch-test:5000}"
echo "  api_key:   ${TESTER_API_KEY:-pdf-dispatch-test-key}"
echo "  data_path: ${TESTER_DATA:-/data}"
echo ""

# ── Install dependencies ───────────────────────────────────────────────────────
echo "Installing Python dependencies..."
pip install -r requirements.txt -q
echo ""

# ── Wait for pdf-dispatch to be ready ─────────────────────────────────────────
SERVER="${TESTER_SERVER:-http://pdf-dispatch-test:5000}"
echo "Waiting for pdf-dispatch at ${SERVER}..."
MAX=30
i=0
until wget -qO- "${SERVER}/healthz" > /dev/null 2>&1; do
    i=$((i + 1))
    if [ $i -ge $MAX ]; then
        echo "ERROR: pdf-dispatch not reachable after ${MAX}s — aborting."
        exit 1
    fi
    printf "."
    sleep 1
done
echo " OK"
echo ""

# ── Run pytest ────────────────────────────────────────────────────────────────
ARGS="${PYTEST_ARGS:--v --tb=short}"
echo "Running: pytest ${ARGS}"
echo ""

exec python -m pytest $ARGS
